// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5uerz0P1Ss837qUQHQBp1wNSWUe62kzY',
    appId: '1:283818545001:android:4a59c3e70517fc461237f8',
    messagingSenderId: '283818545001',
    projectId: 'ownchat-8ba71',
    storageBucket: 'ownchat-8ba71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUXw1C8yuyyx7ofG6qQLn1c3ohEwfS9Mc',
    appId: '1:283818545001:ios:8d6f042ae9e5fd1c1237f8',
    messagingSenderId: '283818545001',
    projectId: 'ownchat-8ba71',
    storageBucket: 'ownchat-8ba71.appspot.com',
    androidClientId: '283818545001-0s4v9hc50b5kfrp43msbrb2f51a005rv.apps.googleusercontent.com',
    iosClientId: '283818545001-1eo0196qms0pcmpqq6m9fnc23ojih6lt.apps.googleusercontent.com',
    iosBundleId: 'com.harshRajpurohit.weChat',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQrzPiK3PFenZSoJiFRw6MLtczQ4AKXjI',
    appId: '1:283818545001:web:7765a2ad218fded11237f8',
    messagingSenderId: '283818545001',
    projectId: 'ownchat-8ba71',
    authDomain: 'ownchat-8ba71.firebaseapp.com',
    storageBucket: 'ownchat-8ba71.appspot.com',
  );

}